"""Domain layer: models, enums, policies, validation."""

from __future__ import annotations

from qa_intelligence.domain.enums import (
    ALWAYS_TEST_CATEGORIES,
    CreateStatus,
    DuplicateBasis,
    FeatureType,
    GapSeverity,
    GenerationDirective,
    LinkStatus,
    RequirementGapType,
    RiskLevel,
    ScenarioDisposition,
    ScenarioSource,
    TestCategory,
)
from qa_intelligence.domain.models import (
    AcceptanceCriteria,
    Bug,
    CategoryExclusion,
    CoverageEstimates,
    CoverageReport,
    DuplicateAnalysis,
    DuplicateCluster,
    FeatureAnalysis,
    QAStrategy,
    RequirementAnalysis,
    RequirementGap,
    ScenarioRef,
    TestCase,
    UserStory,
    ValidationIssue,
    ValidationResult,
)

__all__ = [
    "ALWAYS_TEST_CATEGORIES",
    "AcceptanceCriteria",
    "Bug",
    "CategoryExclusion",
    "CoverageEstimates",
    "CoverageReport",
    "CreateStatus",
    "DuplicateAnalysis",
    "DuplicateBasis",
    "DuplicateCluster",
    "FeatureAnalysis",
    "FeatureType",
    "GapSeverity",
    "GenerationDirective",
    "LinkStatus",
    "QAStrategy",
    "RequirementAnalysis",
    "RequirementGap",
    "RequirementGapType",
    "RiskLevel",
    "ScenarioDisposition",
    "ScenarioRef",
    "ScenarioSource",
    "TestCase",
    "TestCategory",
    "UserStory",
    "ValidationIssue",
    "ValidationResult",
]
